### ISSUE TITLE
Missing Icon for C lang

### ISSUE THREAD

**Issue by DoctorApparatus** [file-icons/icons#59]
Hey I just saw that there is no Icon for the C language. Would greatly appreciate if you could make one.

**Comment by Alhadis** [comment]
:wink: There's no need, that's already provided by [another icon-font] (https://github.com/file-icons/MFixx/blob/master/charmap.md#c) distributed with the `file-icons` package. Check the [icon reference](https://github.com/file-icons/atom/blob/master/README.md#icon-reference) of the Atom package for the other fonts.

I apologise for the confusing inverted mess. This package's history has been a real jumble, and for compatibility reasons, we're currently kind of stuck with several separate fonts instead of one consolidated font. :disappeared:
