### ISSUE TITLE
[request] commitizen config files

### ISSUE THREAD

**Issue by bennypowers** [file-icons/icons#85]
Hello again!

Please add [**commitizen** config files](https://commitizen-tools.github.io/commitizen/config/)

- cz.toml
- cz.json
- .cz.json
- cz.yaml
- .cz.yaml

Looks like they maintain a logo at their github org: https://github.com/commitizen-tools

Thanks as always for maintaining this delightful package.

**Comment by Alhadis** [comment]
Thanks mate. 😀

I've added it, but it'll be a while until you see it land in a release. Basically, I've started [work](https://github.com/file-icons/icons/tree/dev) on a huge-ass migration away from [IcoMoon](https://icomoon.io/app/#/select) to a [FontForge](https://fontforge.org/)-powered pipeline (which I should really resume work on…). Assuming it turns out, I'll move the [`config.cson`](https://github.com/file-icons/atom/blob/33f48e94653eef191a4f259f59e20f604de0d0c1/config.cson) from the Atom package repo to this one, and use release assets and an NPM package to host the generated font-files.

That way, I can serve the same thing to both Atom and VS Code automatically, and eliminate the stress of preparing a release manually (which involves so many steps, I have to triple-check everything before publishing anything).
